export const companyTypeOptions = [
  ["LTD", "Limited Company"],
  ["REG_PARTNER", "Registered Partnership"],
  ["NON_REG_PARTNER", "Non-Registered Partnership"],
  ["LTD_BY_GUARANTEE", "Limited by guarantee"],
  ["SOLE_TRADER", "Sole Trader"],
  ["NON_PROFIT", "Non profit"],
  ["CHARITY", "Charity"],
  ["TRUST", "Trust"],
  ["LTD_PARTNER", "Limited Partnership"],
  ["JOINT_STOCK", "Joint-stock"],
  ["COOP", "Cooperative"],
  ["ASSOCIATION", "Association"],
  ["JOINT_VENTURE", "Joint-venture"],
  ["SIMPLE_LTD", "Simple limited company"],
  ["PLC", "Private Limited Company"],
  ["ECONOMIC_INTEREST_ASSOCIATION", "Economic interest association"],
  ["LLP", "Limited liability partnership"],
  ["PENSION_SCHEME", "Pension scheme"],
  ["CORPORATION", "Corporation"],
  ["SOE", "SOE"],
  ["PUBLIC_SECTOR", "Public sector"],
  ["S_CORPORATION", "S corporation"],
  ["SLP", "Scottish limited partnership"]
];
